dist: trusty
sudo: false
language: generic
services:
  - docker

script:
  - bin/ci

notifications:
  slack:
    secure: XL/jZNwrOedo1GJebiGNuGJ+m9Bnu12UsflPw4LS3Z66RArjPDsxFMt5Xuefv4NWq3EEF5WxwbwYb4RMFx1vZwAozBTYcN8gvIZDfbo/aFrcXWNYKapS1OgI18n3rG1ucAlaEvWyiQ5vbNdR16eK9MBMPXetRecfWlleAiQTOy38oOdRYitMauehxKVOtQnFH2bLNs5m78w68vtc8kp3gf5V1E3MtNxSrdmykSNKPMYTGFEpCq3ge4o9cvcEhoOcixwxa/ZqQ/6TFauIuzLqh0PKpK/oWMMTwnVSRES41ak7hQXzpmt3vWsWNW0JEK0copn9ZcjCyT0E7IDuNgRcXK+roS6qQ8Rjli+VWt+CtnKBhYAC8zCuHWRZmiC7h4DtD8irsF9CjbfJR7rvyXTnVelRbDcoPVldHdGyorM76HmDfkHKo9k6wAqy3TdmqpuYLWlxVWytLm2+v7pF7t2cqLNnpBH3936IFAw0F5LWMBEvQ79hoymj8tSF/FGcS8EpuN7q3cVj1VoqTDMfkWQnOyWGXGfa+sVZpgAZTOMWWeFlDdS/tgAF+8iQiXofQfSvY8UCbDnkKWIT4GAugOreW+0YB20TrZY5pm0D1oeRRmvBGOjA6GiYw9YVJ/djLIgT6jdUS53ogvrqe5sUiWdesGB2zw1WUnUg67SQXWU6x60=
