dist: trusty
sudo: false
language: generic
services:
  - docker

script:
  - travis_wait 60 bin/ci

notifications:
  slack:
    secure: jZHciD1x8EbKDiuAi5AdfSEDzODoWZtAeh9RpfCo5MdAp1kvtXP2Kmgx2pw9/NucPuJB+VPDs7yjF8uqcU4p9A6qxvhTKjpWItUy1+rQ6P4oceoTKZZJLw2UgBDCvUuvaMcs0HKRC+6X8xVqvGV0ZTYfYU4ZK1tvgWbnWJ6rcshPnYGkFG4sSu0SuTDUvkBjVr2BOW9yXJ+t4cqsTMU40PeUCxa1sKR5vC+6aN9kSlRhiH4cxs4XXKyBTn0x3WTyu5S3UGIxmTlNlB2cQ1uZ0OZv35TjZxNeXbb+L9Zuq2pI7tIeEQWxAiO/yB9Y8NptRlWPnjAz6wBsJapv5EdE2l8GuY5CfNtjIP7GmyjlLjrOq3pOgfZ9X8k3BuLxFu7kPLYprfSIoeXPC4PQ+liwF5oYugr4hbVwtRO4kVqqw4qptHIWsJecFNKnsotOLLiIoA6oedIq03ihRJeNzVeet3Fv02iuenhrdwtawsv5y9g4bcIQooJJDc8uHJqjHOwkZYuZLJx8aP5kNUD907OERzB0z5GN98w5CJlDMxJQ8//Ck+6DZnLf0S2BukZKKUdRhgo3pZNkVUmzmGZP2pcZROddfsq6aYztuRw9n4h+FrQKfpM08afOqTTtKiiTK3GUQaAyLj+/LX+yJGI9fi51e9stcLvjJtSkVHkMY1QgZaY=
