dist: trusty
sudo: false
language: generic
services:
  - docker

script:
  - travis_wait 60 bin/ci

notifications:
  slack:
    secure: olJK0BWugvdbxe9hWeZFdNedvdGPLKh0SF2PmNEHlK0LVsq0JN25UHI/2JFw0lB/MX3M23YeX+RbfGAjs3LeS+6RaBggZUzPVQhDibdJvKea2kLFJ3Q7TNZg7202YCD9aLLqFdsWvDeKVr68qbxRqj/zCnq1/PQ1i+RvCPGhtmNMzOwRaguucfh0c4ph2PrYmChVt/89NxtH9J8LkPB6kJ0ZKvFEK8lVSGFOAd1ZrwtbuOJmv1BW4Rui7dhDRzK++zzIvbf1ESD+2rTPHF0QGgPHmRb5k78uG/CUoLwR08QDR6iacpSjjs5rOILixuA5CDKKNIrrFUfragaZT4GaTHkwoEkuVryrabXvQeFBuPvbPn2LlHoc2uzGI+lAvgrtsHmBDki7B4EzOXlzwe/DJ+NXbTUjyWedXeEwL27bMPMGjPO3TvOwSCdS4w4zjPjbxKE5qASfVNABVGtkvGStcrQiGm10Kq2ANCduDTAgLh6gtpI65ticJJ2JIhNrB783y2Oc7BdvrWYWzbdWHSoC9uQDew2VGC0T2usr0IAiVF2CdXWl4kEoCNaA6JSm0uJkxh2K4JyUnutG9Uflj5v1wCoKPcmoPO/l2EmUYKG6L6KWinBnNYW/v22VACHTu37WHKrent7hPNWnc7YaiJwF/XIi/IACnI4grIWRsFTiNT8=
